# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af8090991699f8eaf225ffadc0fc8e3b83c4134b9b89431757a137314ae02c826f26e062ad2177ffacaf797e5eea269981dc246f5d147ce9b5f331cacf9c400c

test:
  secret_key_base: e4560449b12926fd9614fada16a2cf5aa4c2d8ad0704437f7e7a18482717eba3978b91196973562613d3a690141a6aee7bf2349a81b646acba2488b4db543732

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
